############## PRODUTOS

      GET http://localhost:3003/produtos

      ###
      POST http://localhost:3003/produtos
      content-type: application/json

      {
            "nome": "Notebook",
            "descricao": "Notebook Top das galáxias",
            "preco": 3500.00
      }

      ###
      PATCH http://localhost:3003/produtos/1
      content-type: application/json

      {
            "nome": "Notebook Gamer"
      }

      ###
      DELETE http://localhost:3003/produtos/1
      content-type: application/json

############## CATEGORIAS

      GET http://localhost:3003/categoria

      ###

      POST http://localhost:3003/categoria
      content-type: application/json

      {
            "nome": "Consoles",
            "descricao": "Consoles de várias empresas"
      }

      ###
      PATCH http://localhost:3003/categoria/1
      content-type: application/json

      {
            "nome": "Consoles"
      }

      ###
      DELETE http://localhost:3003/categoria/1
      content-type: application/json

############## FILMES

      GET http://localhost:3003/filme

      ###
      POST http://localhost:3003/filme
      content-type: application/json

      {
            "titulo": "O Máskara",
            "duração_minutos": 101,
            "descricao": "A vida do tímido e socialmente desajeitado bancário Stanley Ipkiss muda completamente quando ele encontra no mar uma máscara que possui o espírito do deus escandinavo Loki."
      }

      ###
      PATCH http://localhost:3003/filme/1
      content-type: application/json

      {
            "titulo": "O filho do do Máskara"
      }

      ###
      DELETE http://localhost:3003/filme/1
      content-type: application/json

############## PESSOAS

      GET http://localhost:3003/pessoa

      ###
      POST http://localhost:3003/pessoa
      content-type: application/json

      {
            "nome": "Rodrigo Nascimento",
            "idade": 38,
            "escola": false
      }

      ###
      PATCH http://localhost:3003/pessoa/1
      content-type: application/json

      {
            "escola": "Não"
      }

      ###
      DELETE http://localhost:3003/pessoa/1
      content-type: application/json


############## POKÉMONS

      GET http://localhost:3003/pokemon

      POST http://localhost:3003/pokemon
      content-type: application/json

      {
            "nome": "Gloom",
            "nivel": 20,
            "tipo": "Grama",
            "treinador": "Érica"
      }

      ###
      PATCH http://localhost:3003/pokemon/2
      content-type: application/json

      {
            "nome": "Bellosom"
      }

      ###
      DELETE http://localhost:3003/pokemon/1
      content-type: application/json