GET http://localhost:3001/produtos


###
POST http://localhost:3001/produtos
content-type: application/json

{
      "name": "Notebook",
      "descricao": "Notebook Top das galáxias",
      "preco": 3500.00
}

###
PATCH http://localhost:3001/produtos
content-type: application/json

{
      "name": "Notebook Gamer"
}